server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: vdp
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:8080}
        port: 8719
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=db1;encrypt=true;trustServerCertificate=true;}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  redis:
    host: ${SPRING_REDIS_HOST:127.0.0.1}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:root}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.vdp.entity # 别名扫描包
logging:
  level:
    com.pingo: debug